workflows:
  android-build-only:
    name: Build existing Android APK
    max_build_duration: 30

    environment:
      java: 17

    scripts:
      - name: Build APK with Gradle
        script: |
          ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk
